# Generated by Django 5.2.7 on 2025-10-26 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('Account_id', models.AutoField(primary_key=True, serialize=False)),
                ('Account_no', models.CharField(max_length=20, unique=True)),
                ('Account_type', models.CharField(max_length=50)),
                ('Branch_name', models.CharField(max_length=100)),
                ('Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Status', models.CharField(default='Active', max_length=20)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BankAccount',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_number', models.CharField(max_length=10, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('Address', models.CharField(max_length=10, unique=True)),
                ('Aadhar_number', models.CharField(max_length=12, unique=True)),
                ('Pan_number', models.CharField(max_length=12, unique=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('Transaction_type', models.CharField(max_length=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Transaction_date', models.DateTimeField(auto_now_add=True)),
                ('Account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_app.bankaccount')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='Customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='bank_app.customer'),
        ),
    ]
